### ISSUE TITLE
validator-core - add hability to load data to PostgreSQL in a custom schema

### ISSUE THREAD

**Issue by cboucheIGN** [IGNF/validator#107]
Database connection is set from environment variables.

- VALIDATOR_DB_URL 
- VALIDATOR_DB_USER
- VALIDATOR_DB_PASSWORD
- VALIDATOR_DB_SCHEMA

**Comment by cboucheIGN** [comment]
- [ ] skip CREATE TABLE if already exist
- [ ] create schema if not exist

**Comment by cboucheIGN** [comment]
- [ ] Transform WKT Text to WKT geometry
  * when reading File or in post process ?

**Comment by mborne** [comment]
Version changed to "4.0.0-SNAPSHOT" (3.4 branch for GpU 3.3.x), break change incoming in metadata (identifier -> identifiers) for GpU 4.x (please wait before release)

**Comment by mborne** [comment]
Good job : 

Version changed to "4.0.0-SNAPSHOT" (3.4 branch for GpU 3.3.x), break change incoming in metadata (identifier -> identifiers) for GpU 4.x (please wait before release)

Maybe :

* Remove VALIDATOR_ prefix to avoid duplicating `DB_URL`, `DB_USER`, `DB_PASSWORD` already defined for other projects (dsr)

So far : 

```bash
export VALIDATOR_DB_URL=jdbc:postgresql:validator-test
export VALIDATOR_DB_USER=postgis
export VALIDATOR_DB_PASSWORD=postgis
# provides a nice message : PSQLException: FATAL: database "validator-test" does not exist
mvn clean package
# and this works globally works (some test to be fixed)
createdb validator-test
psql -d validator-test -c "CREATE EXTENSION postgis"
mvn clean package
```

```
[ERROR] Failures: 
[ERROR]   DgprApplicationTest.testDocument:94 expected:<0> but was:<46>
[ERROR]   DgprApplicationTest.testDocumentNotOk:273 expected:<2> but was:<0>
[ERROR]   DgprApplicationTest.testDocumentNotOkTolerance10noSafe:184 expected:<2> but was:<0>
[ERROR]   DgprApplicationTest.testDocumentNotOkTolerance10safe:217 expected:<2> but was:<0>
[ERROR]   DgprApplicationTest.testDocumentOkTolerance5:123 expected:<0> but was:<40>
[ERROR]   DgprApplicationTest.testDocumentOkWithNoTolerance:244 expected:<0> but was:<12>
```

**Comment by mborne** [comment]
> declare geometry type ? declare projection ?

Add `this.getProjection().getSrid()` and check namespace?
