### ISSUE TITLE
validator-core - allow external error configuration file

### ISSUE THREAD

**Issue by mborne** [IGNF/validator#115]
Will allow to use same code but can change messages or error level : 

* [x] Add command option (`--error-config=<path-to-json>`)

```bash
java -jar validator-cli/target/validator-cli.jar document_validator --help | grep error
Missing required options: i, error-config, s
    --error-config <arg>                  Custom error-config.json file to overwrite some error code configuration
```

* [x] Add command to dump error-config model (`java -jar validator-cli.jar error_config > my-config.json`)

```bash
java -jar validator-cli/target/validator-cli.jar error_config | jq -r '.[].code' | head
VALIDATOR_INFO
VALIDATOR_PROJECTION_INFO
VALIDATOR_PROJECTION_LATLON
VALIDATOR_EXCEPTION
DIRECTORY_UNEXPECTED_NAME
FILE_MISPLACED
FILE_UNEXPECTED
FILE_MISSING_MANDATORY
FILE_MISSING_MANDATORY_DIRECTORY
FILE_MISSING_RECOMMANDED
```

**Comment by slafayIGN** [comment]
Do you have an example of this error config file yet ?

**Comment by mborne** [comment]
See https://github.com/IGNF/validator/blob/master/validator-core/src/main/resources/error-code.json (embedded in jar resources)

For GpU and DGPR-TRI, some errors are filtered while reading report (ex : TABLE_UNEXPECTED_ATTRIBUTE WARNING's are removed for `LIB_*` attributes allowed by CNIG standards)
