### ISSUE TITLE
validator-core: JSON model fetch by URL - doesn't fetch all the attributes

### ISSUE THREAD

**Issue by ocruze** [IGNF/validator#204]
"JSON Model fetch by URL" doesn't fetch full tree structure of the model. 

For example, the attributes DATECOG, INSEE and IDURBA for the table [DOC_URBA_COM](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_CC_2013/types/DOC_URBA_COM.json) are missing from the fetched model structure.

Tried with:
* this url : https://www.geoportail-urbanisme.gouv.fr/standard/cnig_CC_2013.json
* this dataset : https://www.data.gouv.fr/fr/datasets/r/074c06d9-eebc-492a-9240-8d75bf0a960b
* Validator v4.0.4

**Comment by mborne** [comment]
As explained offline, the supported JSON model comes with GpU 4.1 ( see PREPROD at https://pp-www.geoportail-urbanisme.gouv.fr/standard/cnig_CC_2013.json from IGN)
