### ISSUE TITLE
validator-core: add Reference attribute in AttributeType

### ISSUE THREAD

**Issue by ClementBouche** [IGNF/validator#27]
In the file model (xml file) reference looks like this :
```xml
    <attribute>
      <id>dc6306f37e364bdb587d1fc79dd7086e</id>
      <name>ID_S_INOND</name>
      <description>Valeur vide interdite</description>
      <type>String</type>
      <nullable>false</nullable>
      <reference>N_prefixTri_INONDABLE_suffixInond_S_ddd.ID_S_INOND</reference>
    </attribute>
```

Reference respect following format : TABLE_NAME.ATTRIBUTE_NAME

* add Reference Attribute to AttributeType
* add getTableReference and getAttributeReference methods to access directly to TABLE_NAME or ATTRIBUTE_NAME

**could impact tests on Xml model serialisation**

**Comment by MFrangi** [comment]
job done with #73
