### ISSUE TITLE
Amélioration de la documentation

### ISSUE THREAD

**Issue by mborne** [IGNF/validator#271]
* Réorganisation du README.md principal (simplification de la présentation des fonctionnalités, suppression doublon d'information, reprise de la présentation de la documentation technique...)
* Ajout de fiches dédiées pour les commandes (doc/cli.md, doc/cli/document_validator.md,...)
* Ajout d'explication sur la nature du programme (CLI java)
* Intégration de la documentation d'installation rédigée pour l'équipe PCRS

**Comment by mborne** [comment]
Travail en cours sur la branche [issue_271](https://github.com/IGNF/validator/tree/issue_271#validator)

**Comment by mborne** [comment]
Je note qu'il faut aussi traiter l'issue archivée avec [IGNF/validator-schema](https://github.com/IGNF/validator-schema/issues/1)

**Comment by mborne** [comment]
@slafayIGN , pour https://github.com/IGNF/validator-schema/issues/1 est-ce que ça te parait plus clair : https://github.com/IGNF/validator/commit/334ba28c0d14076f35fc7e77464eb77781835c83 ?

**Comment by slafayIGN** [comment]
:+1: tout à fait clair
