### ISSUE TITLE
Permettre la validation de données en entrée au format Geopackage

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/validator#324]
Bonjour,

A priori, le format Geopackage ne semble pas supporté en l'état par le validateur comme format d'entrée ?

Dans le cadre de la refonte des Géostandards Risques (https://github.com/cnigfr/Geostandards-Risques ) c'est le format d'échange qui sera très certainement adopté et ces nouveaux Géostandards seront aussi des candidats sérieux pour le validateur.

Le support de ce format (standard et reposant sur des structures de tables SQLite) serait un plus pour le validateur.

**Comment by mborne** [comment]
Bonjour @gcebelieu ,

Pour la validation des données PCRS Vecteur, nous avons été amené à introduire le concept de fichiers [MultiTable](https://github.com/IGNF/validator/blob/v4.4.1/validator-core/src/main/java/fr/ign/validator/model/file/MultiTableModel.java#L16-L40).

Dans le principe, on utilise le format CSV en pivot pour la validation. Dans le cas du GML, on convertit le fichier `data.gml` en `data.vtabs/{nom-table}.csv` à l'aide de ogr2ogr. Pour GeoPackage, avec un peu de chance, il suffira de procéder de même en autorisant `.gml` et `.gpkg` pour les fichiers "MultiTable".

Mickaël

PS : Nous ne l'avons pas fait dans l'attente d'un cas réel à traiter car il faut généralement tâtonner les options "ogr2ogr" utilisée lors de la conversion en CSV.

**Comment by cboucheIGN** [comment]
Bonjour,

Issue traité, livrée en version v4.4.5.

Clément

**Comment by mborne** [comment]
@cboucheIGN j'ai repéré qu'on ne documentait pas [le support de l'extension .gpkg pour les fichiers "multi_table"](https://github.com/IGNF/validator/tree/master/validator-core/src/main/resources/schema#filetype).

Après ça, on pourra fermer l'issue.

**Comment by mborne** [comment]
Traité, je ferme pour y voir clair sur les issues (ping @cboucheIGN )
