### ISSUE TITLE
validator-core(ErrorCodes): WKT attribute

### ISSUE THREAD

**Issue by cboucheIGN** [IGNF/validator#84]
WKT attribute is not understand by final users.

Two solutions:
1/ In validation change WKT field to "Géometrie".
2/ After validation change "WKT" attribute to "Géometrie" while reading report.

I prefer solution 2

**Comment by mborne** [comment]
> I prefer solution 2

Same here...

**Comment by mborne** [comment]
=> Rename "WKT" in PHP ReportReader
